micronaut:
  application:
    name: demo

#datasources:
#  default:
#    url: jdbc:mariadb://localhost:3306/db
#    driverClassName: org.mariadb.jdbc.Driver
#    username: root
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: MYSQL

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: ''

#datasources:
#  default:
#    url: jdbc:mysql://localhost:3306/db
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ''

jpa.default.properties.hibernate.hbm2ddl.auto: update
